WELLS
NAME=Well_1 TYPE=I I= 31 J= 113 K=1 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=2 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=3 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=4 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=5 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=6 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=7 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=8 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=9 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=10 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=11 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=12 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=13 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=14 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 31 J= 113 K=15 DIA=0.50 SKIN=0 DIR=Z
NAME=Well_2 TYPE=P I= 92 J= 132 K=1 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=2 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=3 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=4 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=5 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=6 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=7 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=8 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=9 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=10 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=11 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=12 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=13 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=14 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 92 J= 132 K=15 DIA=0.50 SKIN=0 DIR=Z
NAME=Well_3 TYPE=P I= 101 J= 70 K=1 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=2 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=3 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=4 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=5 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=6 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=7 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=8 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=9 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=10 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=11 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=12 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=13 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=14 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 101 J= 70 K=15 DIA=0.50 SKIN=0 DIR=Z
NAME=Well_4 TYPE=P I= 38 J= 33 K=1 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=2 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=3 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=4 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=5 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=6 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=7 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=8 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=9 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=10 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=11 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=12 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=13 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=14 DIA=0.50 SKIN=0 DIR=Z
	 	 	 	 	 I= 38 J= 33 K=15 DIA=0.50 SKIN=0 DIR=Z
END WELLS
